name: test
on:
  push:
    branches: [ master ]
    
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [test1, test2]
    env:
      VALUE: ${{matrix.value}}
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run:  echo "::set-output name=test::step1-${VALUE}"
      - id: step2
        run:  echo "::set-output name=test::step2-${VALUE}"
        
  two:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [test1, test2]
    needs: [one]
    steps:
      - run: echo ${{needs.one.outputs.output1}} ${{needs.one.outputs.output2}}
