name: test
on:
  push:
    branches: [ master ]
    
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [test1, test2]
    env:
      VALUE: ${{matrix.value}}
    outputs:
       test1-output1: ${{ steps.step1.outputs.test1-output1 }}
       test2-output1: ${{ steps.step1.outputs.test2-output1 }}
       test1-output2: ${{ steps.step2.outputs.test1-output2 }}
       test2-output2: ${{ steps.step2.outputs.test2-output2 }}

    steps:
      - id: step1
        run:  echo "::set-output name=${VALUE}-output1::step1-${VALUE}"
      - id: step2
        run:  echo "::set-output name=${VALUE}-output2::step2-${VALUE}"
        
  two:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [test1, test2]
    env:
      VALUE: ${{matrix.value}}
    needs: [one]
    steps:
      - run: |
          EXAMPLE='needs.one.outputs.{{ matrix.value }}-output2'
          echo ${{needs.one.outputs.test1-output1}} ${{ EXAMPLE }}
          #echo ${{needs.one.outputs.test1-output1}} ${{needs.one.outputs.$EXAMPLE-output2}}
          #if [ $VALUE == "test1" ]; then
          #  echo ${{needs.one.outputs.test1-output1}} ${{needs.one.outputs.test1-output2}}
          #elif [ $VALUE == "test2" ]; then
          #  echo ${{needs.one.outputs.test2-output1}} ${{needs.one.outputs.test2-output2}}
          #fi
